/// Actions produced by the event handler and consumed by the action dispatcher.
#[derive(Debug)]
pub enum MenuAction {
    Open,
    Delete,
    Edit,
    Save,
    Rename,
    Kill,
    Reload,
    MoveSelection(i32),
    AppendToInput(char),
    DeleteFromInput,
    RemoveLastWord,
    TogglePreview,
    ToggleHelp,
    HideConfirmation,
    EnterRenameMode,
    ExitRenameMode,
    CloseErrorPopup,
    ToggleListMode,
    EnterCreateNameMode,
    ConfirmCreateName,
    CreateFromLayout,
    ExitCreateMode,
    Exit,
    Nop,
}
